-- Criando banco de dados
CREATE DATABASE BD_KOSMANAGER;

-- Colocando ele em uso
USE BD_KOSMANAGER;

-- Criando tabelas
CREATE TABLE TB_OPERADOR_PRINCIPAL (
TB_OPERADOR_PRINCIPAL_ID INTEGER primary key NOT NULL auto_increment,
TB_OPERADOR_PRINCIPAL_NOME varchar(120) NOT NULL,
TB_OPERADOR_PRINCIPAL_EMAIL varchar(256) NOT NULL,
TB_OPERADOR_PRINCIPAL_SENHA char(8) NOT NULL
);

CREATE TABLE TB_STATUS(
TB_STATUS_ID INTEGER primary key NOT NULL auto_increment,
TB_STATUS_NOME varchar(14) NOT NULL
);

CREATE TABLE TB_NIVEL_ACESSO(
TB_NIVEL_ACESSO_ID INTEGER primary key NOT NULL auto_increment,
TB_NIVEL_ACESSO_NOME varchar(120) NOT NULL
);

CREATE TABLE TB_FUNCIONARIO (
TB_FUNCIONARIO_ID INTEGER  primary key NOT NULL auto_increment,
TB_FUNCIONARIO_NOME VARCHAR(120)   NOT NULL ,
TB_FUNCIONARIO_EMAIL VARCHAR(256)   NOT NULL ,
TB_FUNCIONARIO_SENHA CHAR(8)   NOT NULL ,
TB_STATUS_ID INTEGER NOT NULL,
TB_NIVEL_ACESSO_ID INTEGER   NOT NULL 
);
  
  CREATE TABLE TB_FORNECEDOR (
  TB_FORNECEDOR_ID INTEGER primary key NOT NULL auto_increment,
  TB_FORNECEDOR_NOME varchar(120) not null ,
  TB_FORNECEDOR_PRODUTO varchar (120),
  TB_FORNECEDOR_CONTATO VARCHAR(120) NOT NULL
  );
  
  CREATE TABLE TB_MATERIA_PRIMA (
  TB_MATERIA_PRIMA_ID integer primary key NOT NULL auto_increment,
  TB_MATERIA_PRIMA_NOMENCLATURA varchar(120),
  TB_MATERIA_PRIMA_MARCA varchar(120),
  TB_MATERIA_PRIMA_LOTE INTEGER NOT NULL,
  TB_MATERIA_PRIMA_DT_VAL DATE NOT NULL,
  TB_FORNECEDOR_ID INTEGER NOT NULL,
  TB_FUNCIONARIO_ID INTEGER NOT NULL
  );
  
  CREATE TABLE TB_PRODUTO_MANU(
  TB_PRODUTO_MANU_ID INTEGER NOT NULL primary key auto_increment,
  TB_PRODUTO_MANU_NOME varchar(120) NOT NULL,
  TB_PRODUTO_MANU_MARCA varchar(120) NOT NULL,
  TB_PRODUTO_MANU_DT_FAB date NOT NULL,
  TB_PRODUTO_MANU_DT_VAL DATE NOT NULL,
  TB_PRODUTO_MANU_LOTE integer NOT NULL
  );
  
  
CREATE TABLE TB_ESTOQUE_MATERIA_PRIMA (
TB_ESTOQUE_MATERIA_PRIMA_ID INTEGER primary key  NOT NULL auto_increment,
TB_ESTOQUE_MATERIA_PRIMA_QUANTIDADE INTEGER   NOT NULL ,
TB_MATERIA_PRIMA_ID INTEGER   NOT NULL ,
TB_FORNECEDOR_ID INTEGER   NOT NULL 
);

CREATE TABLE TB_ESTOQUE_PRODUTO_MANU (
TB_ESTOQUE_PRODUTO_MANU_ID INTEGER primary key  NOT NULL auto_increment,
TB_ESTOQUE_PRODUTO_MANU_QUANTIDADE INTEGER   NOT NULL ,
TB_PRODUTO_MANU_ID INTEGER   NOT NULL
);

CREATE TABLE TB_SOLICITACAO(
TB_SOLICITACAO_ID INTEGER NOT NULL primary key auto_increment,
TB_MATERIA_PRIMA_ID INTEGER   NOT NULL
);

CREATE TABLE TB_REQUISICAO(
TB_REQUISICAO_ID INTEGER NOT NULL primary key auto_increment,
TB_PRODUTO_MANU_ID INTEGER   NOT NULL
);

CREATE TABLE TB_VENDA (
TB_VENDA_ID INTEGER NOT NULL primary key auto_increment,
TB_VENDA_QUANTIDADE INTEGER NOT NULL,
TB_PRODUTO_MANU_ID INTEGER NOT NULL,
TB_FUNCIONARIO_ID INTEGER NOT NULL
);

CREATE TABLE TB_CLIENTE (
TB_CLIENTE_ID INTEGER NOT NULL primary key auto_increment,
TB_CLIENTE_NOME VARCHAR(120) NOT NULL,
TB_CLIENTE_CONTATO VARCHAR(120) NOT NULL
);

-- Adicionando as chaves estrangeiras
alter table TB_FUNCIONARIO
add constraint pk_NIVEL_ACESSO_fk_FUNCIONARIO
foreign key (TB_NIVEL_ACESSO_ID)
references TB_NIVEL_ACESSO(TB_NIVEL_ACESSO_ID);

alter table TB_FUNCIONARIO
add constraint pk_NIVEL_ACESSO_fk_FUNCIONARIO
foreign key (TB_NIVEL_ACESSO_ID)
references TB_NIVEL_ACESSO(TB_NIVEL_ACESSO_ID);

alter table TB_FUNCIONARIO
add constraint pk_STATUS_fk_FUNCIONARIO
foreign key (TB_STATUS_ID)
references TB_STATUS(TB_STATUS_ID);

alter table TB_MATERIA_PRIMA
add constraint pk_FUNCIONARIO_fk_MATERIA_PRIMA
foreign key (TB_FUNCIONARIO_ID)
references TB_FUNCIONARIO(TB_FUNCIONARIO_ID);

alter table TB_MATERIA_PRIMA
add constraint pk_FORNECEDOR_fk_MATERIA_PRIMA
foreign key (TB_FORNECEDOR_ID)
references TB_FORNECEDOR(TB_FORNECEDOR_ID);

alter table TB_VENDA
add constraint pk_FUNCIONARIO_fk_VENDA
foreign key (TB_FUNCIONARIO_ID)
references TB_FUNCIONARIO(TB_FUNCIONARIO_ID);

alter table TB_VENDA
add constraint pk_PRODUTO_MANU_fk_VENDA
foreign key (TB_PRODUTO_MANU_ID)
references TB_PRODUTO_MANU(TB_PRODUTO_MANU_ID);

alter table TB_ESTOQUE_MATERIA_PRIMA
add constraint pk_FORNECEDOR_fk_ESTOQUE_MATERIA_PRIMA
foreign key (TB_FORNECEDOR_ID)
references TB_FORNECEDOR(TB_FORNECEDOR_ID);

alter table TB_ESTOQUE_MATERIA_PRIMA
add constraint pk_MATERIA_PRIMA_fk_ESTOQUE_MATERIA_PRIMA
foreign key (TB_MATERIA_PRIMA_ID)
references TB_MATERIA_PRIMA(TB_MATERIA_PRIMA_ID);

alter table TB_ESTOQUE_PRODUTO_MANU
add constraint pk_PRODUTO_MANU_fk_ESTOQUE_PRODUTO_MANU
foreign key (TB_PRODUTO_MANU_ID)
references TB_PRODUTO_MANU(TB_PRODUTO_MANU_ID);

alter table TB_REQUISICAO
add constraint pk_PRODUTO_MANU_fk_REQUISICAO
foreign key (TB_PRODUTO_MANU_ID)
references TB_PRODUTO_MANU(TB_PRODUTO_MANU_ID);

alter table TB_SOLICITACAO
add constraint pk_MATERIA_PRIMA_fk_SOLICITACAO
foreign key (TB_MATERIA_PRIMA_ID)
references TB_MATERIA_PRIMA(TB_MATERIA_PRIMA_ID);

-- relacionar tabela operador principal e cliente